### PR TITLE
take Additional_repositories into account

### PR DESCRIPTION
**Pull request by ThierryO**
This PR should solve https://github.com/r-universe-org/bugs/issues/109 directly. The suggested workaround is not longer needed.

### CODE REVIEW

**Comment by jeroen** [comment]
I appreciate the suggestion, but the problem is that this makes the repository inconsistent, and therefore the end-user who wants to install packages from your universe won't be able to install that package anymore.

We want to be sure that the user can always do:

```r
install.packages("checklist", repos = "https://inbo.r-universe.dev")
```

And that means that the dependencies of your package will have to be either on CRAN or in your universe, because install.packages does not take `Additional_repositories` into account either.

**Comment by ThierryO** [comment]
Good point.

But what when the package depends on a package we can't add to our universe. E.g. the [`ladybird`](https://github.com/inbo/ladybird ) package has `Additional_repositories: https://inla.r-inla-download.org/R/stable`. Adding that package via `Remotes: github::inbo/INLA` fails on R-universe because it is too large...

Should I try to suggest a patch for `utils::install.packages()` to handle this?

**Comment by jeroen** [comment]
> Should I try to suggest a patch for utils::install.packages() to handle this?

You could try that, but I doubt r-core will take it.

Maybe we can try to help fix the INLA package. There is no reason the package has to be that huge, it includes a ton of files that are not needed (e.g. binaries for linux and mac in a windows package, etc).

**Comment by jeroen** [comment]
It looks like the latest stable release of INLA is now slightly under 100MB. Maybe if you update https://github.com/inbo/INLA to this version, that will solve your issue? 

https://inla.r-inla-download.org/R/stable/src/contrib/INLA_21.11.22.tar.gz

**Comment by jeroen** [comment]
I tried to build INLA from source but I can't get it to work :( The packages that they publish somehow have a mix of win/mac/linux binaries.

Looking at CRAN packages that depend on INLA, none of them have a "hard" dependency (imports) but instead they all seem to use `Suggests: INLA` such that the package can be built, even when INLA is not available:

 - https://cran.r-project.org/web/packages/inlabru/index.html
 - https://cran.r-project.org/web/packages/meta4diag/index.html

Perhaps you can also make INLA a `Suggests` in ladybird, such that the package can be built without it? But that requires also that you remove the `@importFrom INLA` and instead replace them with `INLA::function()` calls in `ladybird`. This would make ladybird suitable for CRAN as well.

**Comment by ThierryO** [comment]
I'm trying to move from `Imports: INLA` to `Suggests: INLA`. I'm running into problems when a package depends on another package that also uses `Suggests: INLA`. See https://stat.ethz.ch/pipermail/r-package-devel/2022q1/007715.html for a more elaborate description of the problem.

@jeroen, do you have suggestions to fix this?

**Pull request closed without merging**
